### ISSUE TITLE
raw bug/fr

### ISSUE THREAD

**Issue by gabrielsroka** [flypenguin/okta-cli#18]
`okta-cli raw logs` returns a `target` which is a JSON array (ie, a Python list), but u can't address it. eg, it'd be nice to request `target.0.displayName` or `target[0].displayName`, etc, but this crashes the cli.

**Comment by flypenguin** [comment]
that is most probably something I don't control. the whole point of "raw" is that the response is returned from okta-cli ... "raw", so whatever the API sends is returned as-is. I will still have a look at it, cause on first glance it seemed weird indeed.

**Comment by gabrielsroka** [comment]
i gues what i'm saying is that i can do this

```
okta-cli raw logs --output-fields uuid,actor.id
```

because those are single fields, but if i try to add target

```
okta-cli raw logs --output-fields uuid,actor.id,target
```

i get a json blob, and if i try

```
okta-cli raw logs --output-fields uuid,actor.id,target[0]
```

i get `WARNING: field target[0] either never filled or non-existant.`

and if i try this, it crashes

```
$ okta-cli raw logs --output-fields uuid,target[0].displayName
Traceback (most recent call last):
  File "/home/runner/TryOktaCli/.pythonlibs/lib/python3.10/site-packages/oktacli/cli.py", line 138, in wrapper
    _print_table_from(rv, kwargs["output_fields"], max_len=max_len)
  File "/home/runner/TryOktaCli/.pythonlibs/lib/python3.10/site-packages/oktacli/cli.py", line 57, in _print_table_from
    max([len(str(DottedDict(item)[col])) for item in arr if col in item])
  File "/home/runner/TryOktaCli/.pythonlibs/lib/python3.10/site-packages/oktacli/cli.py", line 57, in <listcomp>
    max([len(str(DottedDict(item)[col])) for item in arr if col in item])
  File "/home/runner/TryOktaCli/.pythonlibs/lib/python3.10/site-packages/oktacli/dotted/collection.py", line 346, in __contains__
    target = self.store[my_key]
KeyError: 'target[0]'


*****************************************************************************
CRITICAL_ERROR: <class 'KeyError'>

Please report at the issues page with details of what you did. Thank you!
-> https://git.io/JJYqi
*****************************************************************************
```
